// <auto-generated />
using BlazorArtGalleryAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorArtGalleryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201014100423_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorArtGallery.Model.ArtDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LargeImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Private")
                        .HasColumnType("bit");

                    b.Property<bool>("SendAFriend")
                        .HasColumnType("bit");

                    b.Property<string>("SmallImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ArtDetail");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ArtistName = "Misti Vanni",
                            Available = true,
                            Description = "vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Love Is the Devil"
                        },
                        new
                        {
                            ID = 2,
                            ArtistName = "Kassi Grist",
                            Available = true,
                            Description = "ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Way We Laughed, The (Così Ridevano)"
                        },
                        new
                        {
                            ID = 3,
                            ArtistName = "Mallissa Barhams",
                            Available = true,
                            Description = "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Undertaker and His Pals"
                        },
                        new
                        {
                            ID = 4,
                            ArtistName = "Cathe Pallaske",
                            Available = true,
                            Description = "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Being Elmo: A Puppeteer's Journey"
                        },
                        new
                        {
                            ID = 5,
                            ArtistName = "Misti Vanni",
                            Available = true,
                            Description = "vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Love Is the Devil"
                        },
                        new
                        {
                            ID = 6,
                            ArtistName = "Kassi Grist",
                            Available = true,
                            Description = "ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Way We Laughed, The (Così Ridevano)"
                        },
                        new
                        {
                            ID = 7,
                            ArtistName = "Mallissa Barhams",
                            Available = true,
                            Description = "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Undertaker and His Pals"
                        },
                        new
                        {
                            ID = 8,
                            ArtistName = "Cathe Pallaske",
                            Available = true,
                            Description = "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin",
                            LargeImageUrl = "images/big-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Private = true,
                            SendAFriend = true,
                            SmallImageUrl = "images/small-images/Rock_On_Stencil_by_spookyjthm777.jpg",
                            Title = "Being Elmo: A Puppeteer's Journey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
